### ISSUE TITLE
Something error happen while importing the theme for vs2015

### ISSUE THREAD

**Issue by fangd123** [lyphtec/solarized#3]
While I import the theme for vs2015, it say "The XML document forbid the DTD and to enable DTD, please Set XmlReaderSetting Dtdprocessing to Parse..."

I have googled it but no solution about it, Do anyone know how to resolve it? Thanks a lot.

**Comment by lyphtec** [comment]
Can you confirm that you are running the latest version of the [Visual Studio 2015 Color Theme Editor](https://visualstudiogallery.msdn.microsoft.com/6f4b51b6-5c6b-4a81-9cb5-f2daa560430b) extension?

![image](https://cloud.githubusercontent.com/assets/804473/9829839/c2965b34-5959-11e5-9eda-f6b394c90d3c.png)

It works fine for me so I'm not sure what the issue you are facing could be?

**Comment by pikausp** [comment]
Hey, I do have the same issue. Latest Color themes is installed
![image](https://cloud.githubusercontent.com/assets/6717146/10697967/db7d8792-79ae-11e5-8372-0fbb39a1abee.png)

**Comment by lyphtec** [comment]
Hi,

As I can't reproduce this issue - I cannot figure out what could be potentially causing it.

Can you try to see if you can unzip the following & importing it?

https://dl.dropboxusercontent.com/u/16564175/VS2015-solarized.zip

**Comment by pikausp** [comment]
Yeah this one worked with no problems

**Comment by jslatts** [comment]
@pikaupet this happens when you save the file from github incorrectly. Clone the repo and grab the file that way or click Raw and save the file with the correct extension. Don't right click the link and "save as".

**Comment by babelshift** [comment]
@jslatts is correct. Viewing raw and saving resolved the issue.
