### ISSUE TITLE
Color settings for Visual Studio 2013

### ISSUE THREAD

**Issue by ferenczy** [lyphtec/solarized#4]
I just would like to note that color settings for Visual Studio 2013 may be also distributed as a theme for Visual Studio 2013 Color Theme Editor extension by Microsoft. It's the same extension as for Visual Studio 2015.

**Comment by lyphtec** [comment]
Cool. Thanks.

The VS2013 settings were created before this extension.

Are the VS2015 settings file compatible or does it need to be created in the VS2013 version of this extension?

**Comment by ferenczy** [comment]
Sorry, I don't know that.
